Upgrade reference to v14 (VS 2015 or later)
This is in preparation to the migration to AyncPackage

(see https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration)

There are 2 issues remaining from this change:

vs-chromium\src\VsChromium\Views\ImageSourceFactory.cs(81,18,81,38): error CS0103: The name 'DefaultIconImageList' does not exist in the current context
vs-chromium\src\VsChromium\Views\ImageSourceFactory.cs(101,22,101,33): error CS0103: The name 'ImageHelper' does not exist in the current context

The two classes have been removed from Microsoft.Internal.VisualStudio.PlatformUI.